---
filename: .cloudbuild/cd/ui.cloudbuild.yaml
github:
  name: company-project
  owner: company
  push:
    tag: R-.*
name: cd-ui3
substitutions:
  _REPO_SETTINGS: -PrepocompanyUrl=http://repo.company.fr/artifactory -PrepocompanyUser=chef -PrepocomapnyPassword=chef
